### ISSUE TITLE
#9 Add personal saving goals

### ISSUE THREAD

**Issue by somaSeb** [SophiaZett/capstone-project_budget-buddy#20]
## Value proposition

- [ ] As a User I would like to edit saving goals so that I can stay on track and achieve my financial goals more effectively.

## Description

![image](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/133811635/0c9c4e07-a799-4ce7-aaf7-a6cd0dc13679)

## Acceptance criteria

- [ ]  if there are no goals, an info text is shown "You do not have any Goals yet!"
- [ ]  when the user clicks the "+" button a window will appear which includes a form
- [ ]  the form should contain fields to insert details for the savings (Name of Goal, Starting Amount, Total Amount) regarding the custom
- [ ]  the form can only be saved if all fields are filled in, otherwise the user gets an error message, to fill in the fields
- [ ]  Starting Amount, means if the user already saved some money or the user can start at 0 Euro
- [ ]  Total Amount is the savings goal, the user would like to hit the goal
- [ ]  the user has two choices; either Cancel or Save Goal (means save the goal)
- [ ]  if the user clicks the "cancel" button, the person sees either its already saved targets or the message that there are no targets yet
- [ ] 

## Tasks

Create the Add Button Component:

- [ ]  Implement a button component that visually represents the “+” button.
- [ ]  Style the button to indicate its purpose (e.g., use a plus icon).
- [ ]  Attach an event handler to the button to trigger the display of the goal form.

Display the Goal Form:

- [ ]  When the user clicks the “+” button, show a modal or overlay containing the goal form.
- [ ]  The form should include input fields for relevant details related to the custom goal (Name of Goal, Starting Amount, Total Amount).
- [ ] All input fields are required

Implement Cancel Functionality:

- [ ]  Within the goal form, add a “Cancel” button.
- [ ]  When the user clicks the “Cancel” button, close the form without saving any data.
- [ ]  Ensure that the user can easily dismiss the form and return to the previous view.

Implement Submit Functionality:

- [ ]  Add a “Save Goal” button within the goal form.
- [ ]  Validate the form inputs when the user clicks the “Save Goal” button.
- [ ]  If the inputs are valid, save the goal data in a global State (for staging purposes).
- [ ]  Provide appropriate feedback to the user (e.g., success message or error notification).

**Comment by ahohnsen** [comment]
I have a few comments on your user story:

**Value Proposition:** 
Please stick to the format we provided you with (**three-liner**: As a ... I want to ... so that...). You mention editing, however, your user story is about **adding** a goal. 

**Acceptance Criteria:**

>  if there are no goals, an info text is shown "You do not have any Goals yet!"

This seems a bit out of the blue; it would be better to specify where this note is located: on the goals-page. 

> when the user clicks the "+" button a window will appear which includes a form

Be more specific here; no new window opens, but a modal does. 

Additionally, you describe what happens when the user clicks the cancel-button. But what happens when they click _save_? Does the modal close and the user returns to the goals-page? Where does the new entry appear - at the top or bottom of the goal list?

Another point: What does _"Currently available amount"_ mean? If no calculation occurs and a default of 0 is displayed, then it should not appear here as it does not provide any value to the user.

**Comment by Miriam-Voelkl** [comment]
is the goals list display in another user story? if not, you could add to the tasks as well because it's a part of your acceptance criteria. otherwise very detailed 👍
