### ISSUE TITLE
#11  persistent data

### ISSUE THREAD

**Issue by somaSeb** [SophiaZett/capstone-project_budget-buddy#27]
## Titel

persistent data (saving goals and transactions) 

## Value proposition

As a User
I want to see my goals persistent
so that I can see my entries even tough i reloaded or left the App earlier 

## Description

![image](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/133811635/9662ad57-4cd7-4fdb-9a57-e3a098c7c61f)

## Acceptance criteria

- [ ]  when the User closes the Application,
- [ ]  the data will still show up when he reopens the Application
- [ ] Specific Goal and Transaction should be persistent

## Tasks

- [ ] Integrate localStorage to relevant UseStates i.e. Transactions and Goals
