### ISSUE TITLE
Managing Saving Account

### ISSUE THREAD

**Issue by nadine-grantz** [SophiaZett/capstone-project_budget-buddy#29]
## Value proposition
As a User I want to transfer funds from my Transaction Balance towards my Saving Account
so that I can distribute the accumalated Saving Balance towards my Saving 

## Description

![Bildschirmfoto 2024-02-19 um 15 17 58](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/152076100/178c9c97-a4cf-4fb8-91c0-1c0a0c7a5911)

## Acceptance criteria

- [ ] implement a form, for transer money from the main account to the savings account
- [ ] the user can only fill in a amount and a date (without cathegory and description)
- [ ] the user can see the Balace of the goals page, called Savings Account Balance
- [ ] the user can see the Balance of all savings, called Total Saving Amount
- [ ] when the user makes a transfer to saving goals, the savings account balance is automatically updated
- [ ] it is possible that the user leaves the money in the savings account and later adds a savings goal or does not assign the money to a goal for the time being
- [ ] all saving goal amounts for each saving are added together and displayed as total saving amount
- [ ] if the user delete a saving goal, the amount saved so far will be transfered in the Total Saving Amount
- [ ] if there are no saving goal a message "you dont have any saving goals" is displayed

## Tasks

- [ ] create a form with amount and date inputs for money transfer to savings account.
- [ ]  No category or description needed. 
- [ ] transers to Savings Account Balance need to be visible in the List below the two forms
- [ ] Use React hooks and localStorage to store and update the input data and the balances. 
- [ ] Validate the input data and perform the transfer (Savings Account Balance must be min. 0 Euro) . 
- [ ] Show the savings account balance on the goals page and the total savings amount on the bottom.
- [ ]  Don’t allow negative transfers or total savings amount. 
- [ ] Update the localStorage and the balances accordingly. Transfer the saved amount to unassigned savings.
