### ISSUE TITLE
Entry Delete Button

### ISSUE THREAD

**Issue by nadine-grantz** [SophiaZett/capstone-project_budget-buddy#3]
## Value proposition

As a User
I want to be able to delete my specific entries
so that i can update the List of income/expenses

## Description

![Bildschirmfoto 2024-02-02 um 10 08 20](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/152076100/b9e159ab-8719-4ac7-a45a-f50b9b13aad6)

## Acceptance criteria

- [ ] On the homepage, there is a list of current income and expenses.
- [ ] Each entry in the list has a delete button.
- [ ] When the user clicks the delete button for a specific entry, that entry is removed from the list.
- [ ] The user can only delete one entry at a time.

## Tasks

- [ ] Create a new component called DeleteButton in the components folder. This component will render a delete button for each entry in the list.
- [ ] Implement logic to remove the entry from the list when the user clicks the delete button.
- [ ] Implement logic to ensure that the user can only delete one entry at a time.
- [ ] Here’s an example of how to create a new component called DeleteButton in the components folder:

```
function DeleteButton({ id }) {
  const handleDelete = () => {
    const newTransactions = transactions.filter((transaction) => transaction.id !== id);
    setTransactions(newTransactions);
  };

  return (
    <button onClick={handleDelete}>Delete</button>
  );
}

```

**Comment by StellaKakarali** [comment]
Looks great!
