### ISSUE TITLE
Transfer Money back to account

### ISSUE THREAD

**Issue by somaSeb** [SophiaZett/capstone-project_budget-buddy#36]
##Title
Transfer Money back to account

## Value proposition

As a user 
I would like to transfer money back from my Savings Account Balance to my Account 
so that I can always access all of my money in any situation

## Description

![image](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/133811635/e4ca54b0-7f11-48b7-840f-281ca82ec14d)

## Acceptance criteria

- [ ]  implement a form, for transer money from the saving account to the main account to the saving account 
- [ ] the user can only fill in an amount 
- [ ]  when the user makes a transfer to main account and the savings account balance  is automatically updated
- [ ] this transfer is a income (the user should see the transfer in the filter option: income and all)

## Tasks

- [ ] Make a form with amount "inputs" for money transfer to savings account.
- [ ]  No category or description needed (exept in the data model, so that every transaction has the same structure) 
- [ ] Transers to main account need to be visible in the List of transactions
- [ ] Use React hooks and localStorage to store and update the input data and the balances
