### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by somaSeb** [SophiaZett/capstone-project_budget-buddy#37]
## Title
Progress Bar

## Value Proposition
As a User
I want to see a progress bar on every goal
so that I can stay motivated in the progress of saving money

## Description

![image](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/133811635/27aba90e-8e3e-4e07-9fe9-7d5f275d88b9)

## Acceptance Criteria

- [ ] when the user adds money to the goal, the progress bar grows relatively

- [ ] when the user takes money out of the goal, the progress bar should shrink relatively

## Tasks

- [ ] Implement a progressbar component that shows visual progress.
- [ ] Dynamic resizing based on current account balance.
- [ ] Defining a formula to translate the account balance into a percentage.
- [ ] Updated progress bar when adding/removing money.
- [ ] Visual animation of progress growth/decline.
