### ISSUE TITLE
Entry Filter Function

### ISSUE THREAD

**Issue by Melonexx** [SophiaZett/capstone-project_budget-buddy#4]
## Value proposition
As a User
I want to be able to filter my income and expense 
so that I have an overview of my expenses or incomes depending on which filter button i clicked

## Description
<img width="161" alt="Bildschirmfoto 2024-02-02 um 10 14 58" src="https://github.com/SophiaZett/capstone-project_budget-buddy/assets/106445085/d6ca48bf-8130-4202-b6ca-7107edd61528">

## Acceptance criteria

- [ ] On the homepage, there is a list of current income and expenses.
- [ ] There are two filter buttons: one for income and one for expenses.
- [ ] When the user clicks the income filter button, only income entries are displayed.
- [ ] When the user clicks the expense filter button, only expense entries are displayed.
- [ ] The user can only apply one filter at a time.

## Tasks

- [ ] Create a new component called FilterButtons in the components folder. This component will render two
- [ ]  buttons: one for income and one for expenses.
- [ ] Implement logic to filter the entries when the user clicks the income filter button.
- [ ] Implement logic to filter the entries when the user clicks the expense filter button.
- [ ] Implement logic to ensure that the user can only apply one filter at a time.
- [ ] Here’s an example of how to create a new component called FilterButtons in the components folder:

```
function FilterButtons() {
  const [filter, setFilter] = useState('');

  function handleFilter(filter) {
    setFilter(filter);
  }

  return (
    <div>
      <button onClick={() => handleFilter('income')}>Income</button>
      <button onClick={() => handleFilter('expense')}>Expense</button>
    </div>
  );
}
```

**Comment by ahohnsen** [comment]
Maybe you can add in the Acceptance Criteria, that the selected filter is visually highlighted (e.g. has another color). At least it looks a bit like that in your wireframes :)
