### ISSUE TITLE
#5 Add "Show All" Button

### ISSUE THREAD

**Issue by Melonexx** [SophiaZett/capstone-project_budget-buddy#6]
## Value proposition
As a User
I want to see all transactions as well as the total amount of incomes - expenses
so that i have again an overview of all incomes and expenses at once

## Description

![Bildschirmfoto 2024-02-08 um 10 41 09](https://github.com/SophiaZett/capstone-project_budget-buddy/assets/151823139/77ec78c4-02d8-40e3-be56-325b1b8b1df1)

## Acceptance criteria

- [ ] On the homepage, there is a list of current income and expenses.
- [ ] There are two filter buttons: one for income and one for expenses.
- [ ] When the user clicks the income filter button, only income entries are displayed.
- [ ] When the user clicks the expense filter button, only expense entries are displayed.
- [ ] The user can only apply one filter at a time.
- [ ] There is a “Show Complete List” button that displays all transactions when clicked.

## Tasks

- [ ] Create a new component called CompleteListButton in the components folder. This component will render
 a button that displays all transactions when clicked.
- [ ] Create a new component called AmountContainer in the components folder. This component will render the
total amount of incomes and expenses.
- [ ] Implement logic to display all transactions when the user clicks the “Show Complete List” button.
- [ ] Implement logic to calculate the total amount of income and expenses.
- [ ] Implement logic to ensure that the user can only apply one filter at a time.

Here’s an example of how to create a new component called CompleteListButton in the components folder:

```
function CompleteListButton() {
  const [showAll, setShowAll] = useState(false);

//...

  return (
    <div>
      <button onClick={() => handleFilter('income')}>Income</button>
      <button onClick={() => handleFilter('expense')}>Expense</button>
      <p>Total amount: {totalAmount}</p>
    </div>
  );
}
```

**Comment by Miriam-Voelkl** [comment]
looks great to me 🐝

**Comment by ahohnsen** [comment]
Same here: the title is soooooooo long! Remember: it should be short and precise :)
